version: '3.8'
services:
 sender:
   build:
     context: ./sender
   depends_on:
     - receiver

 receiver:
   build:
     context: ./receiver
   networks:
    - vision-net
    
networks:
  vision-net:
    name: Vision-net
    driver: bridge