version: '3.8'
services:
 sender:
   build:
     context: ./sender
   depends_on:
     - receiver
 receiver:
   build:
#the network_mode was added here
     context: ./receiver
   ports:
     - "5000:5000" 
